### ISSUE TITLE
Context menu doesn't close automatically after node is deleted.

### ISSUE THREAD

**Issue by NithinRG** [naseemshah/graph-visualizer#4]

**Comment by naseemshah** [comment]
The idea was if there was multiple nodes in the context menu, sometimes we need to delete multiple nodes. like this: 

![gvis issue 2](https://user-images.githubusercontent.com/44234669/81941594-a92d8100-9616-11ea-97e1-e91efbbdaf44.gif)

So think it ould awesome to **close only when the context menu is empty**.

**Comment by naseemshah** [comment]
Now the context menu closes after deleting a node and when it's empty only (which is what we want).

![gvis issue 3](https://user-images.githubusercontent.com/44234669/81967867-2ff35580-9639-11ea-8344-1a9b9352bad5.gif)

This has been fixed in the commit 0283b55 . Thank you @NithinRG and @DheerajChalil for issue reporting.

**Comment by NithinRG** [comment]
> Now the context menu closes after deleting a node and when it's empty only (which is what we want).
> 
> ![gvis issue 3](https://user-images.githubusercontent.com/44234669/81967867-2ff35580-9639-11ea-8344-1a9b9352bad5.gif)
> 
> This has been fixed in the commit [0283b55](https://github.com/naseemshah/graph-visualizer/commit/0283b5597cf1dd0721247469fddd82edbac7d252) . Thank you @NithinRG and @DheerajChalil for issue reporting.

That's what I meant. It should close automatically when empty. Nice feature.
